---
- name: Run application container
  docker_container:
    name: simple-api
    image: "jujubaa/tp-devops-simple-api-backend:latest"  # votre image depuis DockerHub
    pull: true
    recreate: true
    force_kill: true
    networks:
      - name: app_network
    env:
      DATABASE_HOST: database  # Nom du conteneur de la base de données
      DATABASE_PASSWORD: pwd  # Mot de passe de la base de données
      DATABASE_USER: user  # Nom d'utilisateur de la base de données
      DATABASE_NAME: db  # Nom de la base de données
      # Ajoutez d'autres variables d'environnement nécessaires
    restart_policy: always
    state: started
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python