name: Build and Push Docker Images

on:
  workflow_run:
    workflows: ["Backend Tests"]
    types:
      - completed
    branches:
      - main

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-24.04
    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Download test status
        uses: actions/download-artifact@v4
        with:
          name: test-status-${{ github.event.workflow_run.head_sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Verify tests passed
        run: |
          if [ ! -f "backend-tests" ] || [ "$(cat backend-tests | head -n1)" != "SUCCESS" ]; then
            echo "Backend tests did not pass. Stopping deployment."
            exit 1
          fi
          echo "Backend tests passed. Proceeding with Docker build."

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Build and push BACKEND
      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./simple-api  
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api-backend:latest
          push: true

      # Build and push DATABASE 
      - name: Build image and push database
        uses: docker/build-push-action@v6
        with:
          context: ./database  
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api-database:latest
          push: true

      # Build and push HTTPD 
      - name: Build image and push http
        uses: docker/build-push-action@v6
        with:
          context: ./http-server  
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api-httpd:latest
          push: true
